### ISSUE TITLE
np.save

### ISSUE THREAD

**Issue by hely201314** [hulianyuyy/AdaptSign#1]
Hello, while running this code, I encountered the following error on line 71 of seq_scripts. py (np. save ('pred_clip.adapter. npy ', total_conv_sent):ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (540,) + inhomogeneous part

**Comment by hulianyuyy** [comment]
I haven't encoutered this issue. And if you encounter the above error, you are free to comment this line as this is deperacated. I will update the code accordingly.

**Comment by hely201314** [comment]
To solve this problem, just comment out np.save(**) on line 71.
